apiVersion: batch/v1
kind: CronJob
metadata:
  name: datacleaner
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: task
              image: lexisdatacleaner
              command:
                - /bin/sh
                - -c